// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```w
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYf82lJlSKuEBomlUwRCQ6lctwyKZ_Qk',
    appId: '1:300770706123:web:e8ca9c06dd1e92789a514e',
    messagingSenderId: '300770706123',
    projectId: 'facebook-clone-73200',
    authDomain: 'facebook-clone-73200.firebaseapp.com',
    storageBucket: 'facebook-clone-73200.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB33R3FVuMKT6kMQScKhUqt0f9hFMlnWoo',
    appId: '1:300770706123:android:136e80a3061168e09a514e',
    messagingSenderId: '300770706123',
    projectId: 'facebook-clone-73200',
    storageBucket: 'facebook-clone-73200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPy-1t_1PG59E26KcAKZNF6_TlFuIt9jw',
    appId: '1:300770706123:ios:7729760f36c32f2e9a514e',
    messagingSenderId: '300770706123',
    projectId: 'facebook-clone-73200',
    storageBucket: 'facebook-clone-73200.appspot.com',
    iosBundleId: 'com.example.facebookClone',
  );
}
